'm	DET	dem
'ma	DET	einem
'r	PRON	er
a	DET	ein
a	DET	ein
a	DET	ein
àller	PRON	aller
àllewèèj	ADV	vielleicht
àlls	ADV	ständig
àlt	ADJ	alt
àm	ADP	am
àm	ADP	am
àm	ADP	am
àm	PART	am
àn	ADP	an
àn	ADP	an
ànder	PRON	andere
àndersch	ADV	anders
ànna	ADP	in
ànne	ADV	hin
ànschtàtt	ADP	anstatt
ànstàtt	ADP	anstatt
ar	PRON	er
àrig	ADV	arg
àss	CONJ	dass
awer	CONJ	aber
àwer	CONJ	aber
awwer	CONJ	aber
bàll	ADV	bald
beida	PRON	beiden
bi	ADP	bei
bi	ADP	bei
bi	ADP	bei
bim	ADP	beim
biss	ADP	bis
bìssel	DET	bisschen
bständig	ADV	ständig
bstìmmt	ADV	bestimmt
d	DET	die
d	DET	die
d'	DET	die
d'	DET	die
d'	DET	die
d'r	DET	der
d'r	DET	der
d'zither	ADP	seitdem
d’	DET	die
da	DET	den
da	DET	den
dam	DET	dem
dànn	CONJ	dann
dàs	DET	das
dàs	PRON	das
dàs	PRON	das
dàss	CONJ	dass
dàss	SCONJ	dass
de-n-	DET	den
demit	ADV	damit
derbi	PRON	dabei
derbii	PRON	dabei
derfer	PRON	dafür
derre	PRON	diese
dèrt	ADV	dort
des	PRON	dieser
devun	ADV	davon
dì	PRON	dich
dia	DET	die
dìch	PRON	dich
die	DET	die
dini	PRON	deine
dìss	PRON	das
do	ADV	da
dr	DET	der
dr	DET	der
drààn	ADV	daran
drin	ADV	darein
drìnne	ADV	drinnen
drìwe	ADV	drüben
driwer	ADV	darüber
drowe	ADV	oben
drüben	PRON	darüber
druff	ADV	drauf
drum	PRON	darum
drùm	PRON	darum
drunte	ADV	unten
drunter	ADV	darunter
drüsse	ADV	draussen
dü	PRON	du
dur	ADP	durch
dura	ADP	durch
durich	ADP	durch
durrich	ADV	durch
durrich	ADP	durch
ébb	PRON	etwa
ebbis	PRON	etwas
ebbis	PRON	etwas
ebbs	PRON	etwas
ëber	ADP	über
ééndersch	ADV	eher
éérst	ADV	erst
eini	PRON	eine
Ejch	PRON	Euch
em	DET	dem
entlàng	ADP	entlang
ere	DET	einer
erin	ADV	herein
erum	PART	herum
erùm	PART	herum
erumm	ADV	herum
erüss	ADV	heraus
es	PRON	es
éwe	ADV	eben
ewègg	ADV	weg
fàst	ADV	fast
fer	ADP	für
fer	ADP	für
fìr	ADP	für
fìr	ADP	für
firdààs	ADV	feiertags
fìrschi	ADV	vorwärts
for	ADP	für
frìej	ADV	früh
frìejer	ADV	früher
g'sì	VERB	gewesen
g'sìnn	VERB	gewesen
gaje	ADP	gegen
gànz	ADV	ganz
gàr	ADV	gar
gega	ADP	gegen
gege	ADP	gegen
geje	ADP	gegen
géje	ADP	gegen
genüe	ADV	genug
gést	ADV	gestern
gràd	ADV	gerade
gsìì	VERB	gewesen
hà	VERB	have
hab	VERB	habe
hàbb	VERB	have
han	VERB	haben
han	VERB	haben
hàn	VERB	haben
hànn	VERB	haben
hàt	VERB	hat
hàt	VERB	hat
häts	VERB	hat es
hàtt	VERB	hat
hender	ADP	hinter
henger	ADP	hinter
hère	ADV	her
hesch	VERB	hast
het	VERB	hat
het	VERB	hat
hett	VERB	hat
hìnder	ADP	hinter
hìnger	ADP	hinter
hìnne	ADV	hinnen
hìnte	ADV	hinter
hìnter	ADP	hinter
hìnter	ADP	hinter
hìnterschi	ADV	rückwärts
hitt	ADV	heute
hìwe	ADV	hüben
howe	ADV	hieroben
hunte	ADV	hierunten
hüsse	ADV	haussen
ìch	PRON	ich
ìch	PRON	ich
ìerix	ADV	irgendwo
ìhm	PRON	ihm
ihri	PRON	ihre
ìm	ADP	im
ìm	ADP	im
ìn	ADP	in
ìn	ADP	in
ìn	ADP	in
ìn	ADP	in
ìndersch	ADV	eher
ìnger	ADP	unter
isch	VERB	ist
isch	VERB	ist
ìsch	VERB	ist
ìsch	VERB	ist
ìsch	VERB	ist
ìwer	ADP	über
ìwer	ADP	über
ìweral	ADV	überall
ìwermorje	ADV	übermorgen
ìwwer	ADP	über
jétz	ADV	jetzt
jo	PART	ja
kè	PRON	kein
kenn	PRON	keine
küm	ADV	kaum
kurz	ADV	kurz
làng	ADV	lang
lìnks	ADV	links
m'r	PRON	mir
ma	PRON	man
ma	PRON	man
me	PRON	man
meh	DET	mehr
met	ADP	mit
mìch	PRON	mich
mine	PRON	meine
minere	PRON	meiner
mìr	PRON	mir
mìt	ADP	mit
mìt	ADP	mit
mittààs	ADV	nachmittags
momèntààn	ADV	momentan
morje	ADV	morgen
morjets	ADV	morgens
nààchts	ADV	nachts
nawa	ADP	neben
nèèwe	ADP	neben
nieme	PRON	niemand
nìerix	ADV	nirgendwo
nin	ADV	hinein
nit	PART	nicht
nìt	PART	nicht
nìt	PART	nicht
nìtt	PART	nicht
nìtt	PART	nicht
nìwer	ADV	hinüber
noh	ADP	nach
nooch	ADP	nach
noochhèr	ADV	nachher
noochmittààs	ADV	nachmittags
numme	ADV	nur
nüss	ADV	hinaus
obb		ob
obb	SCONJ	ob
odder	CONJ	oder
ohna	ADP	ohne
ohne	ADP	ohne
oowets	ADV	abends
pààr	PRON	paar
rèèchts	ADV	rechts
rin	ADV	herein
rìwer	ADV	herüber
rumm	ADV	herum
rüss	ADV	heraus
s'	DET	die
schunn	ADV	schon
schunsch	ADV	sonst
schunst	ADV	sonst
si	PRON	sie
sì	VERB	sind
sìch	PRON	sich
sìch	PRON	sich
sìch	PRON	sich
sìe	PRON	sie
sìì	VERB	sein
sìn	VERB	sind
sina	PRON	sein
sinn	VERB	sind
sìnn	VERB	sind
sinner	PRON	seiner
sìtter	ADP	seitdem
spéter	ADV	später
spot	ADV	spät
stàtt	ADP	statt
sunndààs	ADV	sonntags
trotzdam	PRON	trotzdem
uf	ADP	auf
uf	ADP	auf
uff	ADP	auf
uff	ADP	auf
uff	ADP	auf
ùff	ADP	auf
um	ADP	um
un	CONJ	und
un	CONJ	und
un	CONJ	und
un	CONJ	und
ùn	CONJ	und
under	ADP	unter
unger	ADP	unter
ungfähr	ADV	ungefähr
unn	CONJ	und
unsera	PRON	unseren
unseri	PRON	unser
üs	ADP	aus
üsmine-n-	PRON	meine
üss	ADP	aus
üss	ADP	aus
üssem	ADP	vom
vìel	DET	viel
vìellicht	ADV	vielleicht
vo	ADP	von
vor	ADP	vor
vorgést	ADV	vorgestern
vorhér	ADV	vorher
vorne	ADV	vorn
vorrüs	PART	voraus
vorwätz	ADV	vorwärts
vu	ADP	von
vum	ADP	vom
vum	ADP	vom
vum	ADP	vom
vum	ADP	vom
vùm	ADP	vom
vun	ADP	von
vun	ADP	von
vun	ADP	von
vun	ADP	von
wahrend	CONJ	während
waje	ADP	wegen
wègg	ADV	weg
wènn	SCONJ	wenn
Wenn	CONJ	wenn
Wënn	CONJ	wenn
wénni	DET	wenig
wénnjer	DET	weniger
wèrdààs	ADV	werktags
wial	CONJ	weil
wìdder	ADV	wieder
wìe	PRON	wie
wievìel	DET	wieviel
wil	SCONJ	weil
wittersch	ADV	weiter
wo-n-	PRON	die
wohrschinlich	ADV	wahrscheinlich
wohrschins	ADV	wahrscheinlich
z'	ADP	zu
z'	PART	zu
ze	PART	zu
ze	PART	zu
ze	ADP	zu
zèllemols	ADV	damals
zeruck	ADV	zurück
zìemlich	ADV	ziemlich
zìmlig	PART	ziemlich
zitter	ADP	seit
zìtter	ADP	seit
zìtter	ADP	seit
zö	ADP	zu
zu	ADP	zu
zue	PART	zu
zue	PART	zu
züe	ADP	zu
zwìscha	ADP	zwischen
zwìsche	ADP	zwischen
zwìsche	ADP	zwischen
!	PUNCT	!
!!	PUNCT	!!!
!!!	PUNCT	!!!
!?	PUNCT	!?
!?!?	PUNCT	!?
""""	PUNCT	""""
<-	PUNCT	<-
<->	PUNCT	<->
'	PUNCT	""""
*	PUNCT	-
+	PUNCT	-
-	PUNCT	-
->	PUNCT	->
.	PUNCT	.
...	PUNCT	...
:	PUNCT	:
;	PUNCT	;
<-	PUNCT	<-
<->	PUNCT	<->
?	PUNCT	?
?!	PUNCT	!?
?!?!	PUNCT	!?
???	PUNCT	?
etc.	PUNCT	etc.
|	PUNCT	-
!	PUNCT	!
!!	PUNCT	!!!
!!!	PUNCT	!!!
!?	PUNCT	!?
!?!?	PUNCT	!?
:	PUNCT	:
;	PUNCT	;
?	PUNCT	?
?!	PUNCT	!?
?!?!	PUNCT	!?
???	PUNCT	?
»	PUNCT	»
«	PUNCT	«
« 	PUNCT	«
»	PUNCT	»
“	PUNCT	« 
”	PUNCT	»
"	PUNCT	"
/	PUNCT	/
