<div style="white-space: pre-wrap; text-align: center">
     <a href="{{ url('/download_txt/E_Hochzit_in_de_50er_Johre.docx') }}" download="E Hochzit in de 50er Johre">Téléchargement (docx)</a>
    <h3> E Hochzit in de 50er Johre </h3>
    vum Raymond Weissenburger
</div>

Mir schriwe ’s Johr 1953. Es isch e Dienschdàà im April. E gröijer, troschtloser Dienschdàà, ohne Wind fer die Wolike ze vertriwe wie schunn de gànze Morje de Himmel bedecke un nit ferti wäre mit niessle.  Fàscht kennt m’r glauwe es wärd e normàler Dienschdàà, wenn nit gànz àm End vum Dorf, im e Fàchwärikhüs mit hellbloï àng’strichene Rijelwänd, mit griene Läde, mit zwei bescheidene Vordächer uf sinere Vordersit un mit‘eme ànspruchslose owere Stock, wenn nitt in dem Hüs e so groβi Ufreijung herrsche dät. Uf Hochdüre laufe do inne d’Vorbereitunge fer d’Hochzit vum Marikel, mit‘em Güscht, e Büe vum Dorf.
’ s Groβe ìserne Hofdor steht ìnlàdend wit offe, de Hoft isch süefer g’fäjt, de Brunne isch frei vun sine Eimer, d’Stàffel üs Sàndstaan isch frisch àbg’wäsche worre, d’Fenschterschììwe glitzere, d’Feschtlichkeite kenne ànfànge. Anfànge ? Wo denke n’r ànne ! Es isch erscht àcht Ühr àm Morje, m’r hàn noch gànze zwei Stund Zit fer ze bummle bevor d’Kircheglocke ànfànge ze lite. Hàw ich jetz g’sààt „bummle?“ Awer naan ! Hinter de Ingàngsdier beschäftige sich mindeschtens e dutzend Händ, un genau so viel Fieβ kumme un gehn in dem kurze, schmàle Gàng wie noch Javel schmecke duet un wie in d’Kiche un in d’Stub fiehrt.
An däre Stell dät ich jetzt gern, mit eirem Erlaubnis, e Zwischebemerikung màche, gràd fer die Zit wie ich brüch fer iwer d’Schwell vun däre Stub ze gehn zü däre ich e gànz b’sunderi Züneigung hàb.

	Es sin Erinnerunge àn mini friej Kindheit, wenn mir àls Sunndàà-Nochmiddààs, noch de Veschper, mini Groβeltere b’süecht hàn. Ich erinner mich noch gànz genau àn die Eckbànk uf die ich mich g’setzt hàb un die noch Wàchs g’schmeckt het, àn de Groβvàdder wie immer àm Fenschter g’sässe n’isch vun wo m’r uf d’Stroβ gickle het kenne, àn d’Groβmueder wie üs de Schlofkàmmer kumme n’isch, so scheij un ängschtlich wie e jungi Sunne wie friej àm Morje üs de Nàcht rüskummt, àn denne Ticktack vun de Stàndühr, au àn des Buffet näwe de Dier uf dem e schwàrzes Kritz mit‘eme wisse, gekritzigte Heilànd g’stànde n’isch, àn denne griene Guβofe wie so e herrlichi, àngenähmi Wärme vun sich gän het, àwer d’scheenscht un d’bezaubernscht Erinnerung vun däre Zit, des sin die fiene, fàscht durchsichtige Elfebeinhänd vun minere Dànte wie uns jedesmol wenn mir kumme sin, de verlockenschd Savarin präsentiert het der mir schun s’Wàsser im Mül het màche zàmme laafe wenn ich numme g’heert hàb, dàss m’r zü de Grogehn. Un gràd wàje dem Savarin hàw ich die b’sunder Beziehjung zü däre Stub. Fer mich àls Kind, isch der Nàpfkueche s’wundervollschte Dessert gewänn. Un wie geglänzt het der wenn ne die zwei wisse Händ uffeme silveriche Tàblett eringetrauje hàn ! M’r het fàscht glauwe kenne mini Dànte het ne in e zàrter Morjetau üs Likör getunkt g’hett, so frisch un froh het der üsg’sähn ! Un wàs fer e köschtlicher G’schmàck wie er dànn vun sich gän het wenn ’s Leffele in dem weiche, ockergähle Kueche versunke n’isch ! Wie wenn’s in e ätherischi Màss ingetaucht wärd worre ! Herrgott, wàs fer e G’schmàck ! 
Tàtsàch isch, dàss es de Tràwereschnàps gewänn isch wie so köschtlich einem d’Nàselöchle gekitzelt het. Un wenn dànn so e Stickele uffem Leffele geläje n’isch, dànn het m’r vorsichtig, dàss jo nix ràbfàlle duet, des Leffele in d’Heh vum Mül gebrocht, het dànn gànz àndächtig g’hàlte, fàscht so àndächtig wie wenn m’r d’Kommunion empfànge dät, het sini Zung durch d’offene Lippe vorg’schickt fer numme e bissele drààn ze schlecke, un wenn m’rs nimmi üsg’hàlte het vor lütter Glickseligkeit un ‘ s Verlànge nimmi ufzehàlte gewänn isch, dànn het m’rs ins Mül g’fiehrt, mit gràd so viel Lièb mit däre de Hochzitter sini jung Frau in de Hochzitsnàcht iwwer d’Schwell vum Schlofzimmer fiehre duet.

Üs däre „Savarin-Stub“ kummt uns hit ken Tràwere-Duft entgàje, àwer e stàricker G’schmàck vun Linöl mit dem m’r wohrschins de Bodde g’wienert het. Sie isch leer vun ihre Möwel, d’Trennwànd wie d’Schlofkàmmer vun de eijetliche Stub getrennt het isch àbmontiert demit meh Plàtz isch, es sin Disch un Bänk ufg’stellt worre fer 55 Persone. 
Die Disch sin so feschtlich  geziert wie de Altàr vun de Kirch àn Mariä-Himmelfàhrt, wenn ihr mir denne Verglich erlauwe. Màkellose Däller, stràhlend, glänzende Gläser, wissi Serviette, s’ Feschtdàà-B’steck, hàlt. Ah! wie het des àlles geglitzert un g’funkelt, fàscht so wie d’Auje vun de Hochzittere glänze wäre wenn se noochhäre vorem Pfàrrer ihr „ja, ich will“ flüschtere wurd. M’r het schnell de Rundgàng vun de Stub gemàcht, sie isch nit groβ, wohrschins mues m’r sich e bissel zàmmerucke später, àwer scheen isch se hit mit ihre wisse Dischdecke, ja, wie e Kirch mit viel Altär.

	Awer gehn m’r doch schnell in d’Kiche, do wo d’Köche, wie speziell vun Owerstaanbàch àngereist isch, schun zitter àm Sàmschdàà schàffe duet ! Jetz stelle ihr eich die berechtigt Fröj worum  so e üsergewehnlichi Ufmàchung fer so e einfàchi Hochzit ? Einfàchi Hochzit ? Es isch nie e einfàchi Hochzit g’fiert worre in unsere Derfle ! Un die Hochzite vun friejer sin in keiner Wììs verglichbàr mit denne wie hitzedàss g’fiert wäre; dem entsprechende Ereignis het m’r sich àngepàsst. Un des Ereignis isch vunere unermeβliche Bedittung gewänn, àlso het m’r au dementsprechend g’fiert. Es isch des Fàmiliefescht „par excellence“ gewänn, wenn ich mir denne Üsdruck erlauwe därf, un do het nàdierli keini vun denne zwei Pàrtéie zeruckstehn welle. Des wärd e Schànd gewänn wenn m’r wenijer ufgetàfelt hätt g’hett wie zuem Beispiel bim cousin Soundso.  Un gràd wàje dem het sich die Köche schun zitterem Sàmschdàà in de Kiche mit de Vorbereitunge b’schäftigt.

	Do isch jetz de Moment kumme fer ze fröje worum m’r Dienschdààs g’hierot het un nit Sàmschdààs wie hitzedààs. Dodefer gibts zwei wesentliche Grind. Erschtens, weil zü däre Zit ufem Lànd d’Induschtrialisierung noch nit denne Ufschwung gekennt het wie später, do het fàscht jedi Fàmilie noch vunere kleine Làndwirtschàft g’lëbt un somit sin a die Lit nit so àngebunde gewänn wie wenn se inere Fàbrik ihr Geld verdient hätte, àlso hàn se meh iwer ihri Freizit verfieje kenne. De zweite Grund isch bedingt vum e pràktische Zweck un zü glich a vum e religiöse. Pràktisch, weil m’r sich de Sàmschdàà reserviert het fer d’Biscuit-Tàrte ze bàcke un fer s’Kälwel un d’Hiehner ze metze, wàs m’r àm e àndere Dàà màche hätt muen wenn d’Hochzitt àm e Sàmschdàà wärd gewänn. Un dànn, wenn m’r àm e Sàmschdàà g’hierot hätt, do hätt m’r jo numme einer Dàà fiere kenne weil jo de Sunndàà unserem Herrgott g’heert het. Do isch m’r ins Amt gànge, do isch m’r in d’Veschper gànge, ja un wie hätt m’r des iwereins bringe solle mitem Fiere wenn m’r bis in de friehje morje zàmme g’sesse wärd un miteme Schwipps sich ins Bett g’läjt hätt fer de àndere morje mit Kopfweh ins Hochàmt ze gehn ? 
Am Sunndàà üssetze un àm Mondàà widder ànfànge fiere ? Naan, des hätt einem d’gànz Luscht zuem amüsiere verdorwe, àlso het m’r sich fer d’pràktischt Lösung entschiede, die wie de Himmel arràngiert het un züglich a d’Mensche. M’r het àm e Dienschdàà g’hierot !

Die zwei Pàrtéie hàn sich dànn g’einigt fer mitnànder e Kälwel ze kaufe, weil im Moment keins im Stàll verfiejbàr gewänn isch, un des isch a g’metzt worre. Arms Kälwel! ich heer eich jetz vor Mitleid johmere un des Kälwel beduere. Ah! lon m’r doch desmol unseri G’fiehler uf de Sit un saawe m’r, es isch fer e gueter Zweck g’metz worre. Awer, wenns ihm àn de Hàls geht, kànn sich a ’ s g’scheijschte Kälwel nit vorstelle fer de beschte Zweck sin Läwe ze lon un so hetts b’schlosse sich uf de Stell ze räche. Ich verzähl eich wie.

	Gànz frieh àm Sàmschdààmorje isch àlso des Kälwel bim e Büür g’holt worre, m’r het’s in d’Schier vum Groβvàdder gebrocht, wo’s dànn de Metzjer vum Läwe in de Tod befördet het. Es isch dànn àn d’Leiter g’hängt worre, àn de Hinterfies feschtgebunde, àlso, so het’s solle sin,  denn kuem isch’s g’hànge, het sich, post mortem, einer Fueβ in de letschte Zuckunge, vun sinne Fessel g’löst gràd in dem Moment wo de Hochzitter durchg’loffe n’isch. Wàs kumme het muen isch kumme, der Fueβ vum Kälwel het direkt ufs Au vum Hochzitter gepàsst un der het miteme bloïje Au in d’Kirich gehn muen unter de spöttische Bemerikunge vun de Gäscht wie ihm gerote hàn doch nitt mit däre junge Frau e Ehe inzegehn wenn se ihm schun vorhäre e Bloïj Au verpàsst het. Ja, wenn m’r de Schàde het brücht m’r fer de Spott nit sorje... So viel zü de Ràche vum àrme Kälwel.

	Am Mondàà dànn, hàn noch zwei Söi ihr Läwe g’lon un do isch de gànze Dàà druf gànge. Jedi Fàmile het eini g’stellt, schun wäje de Prinzipié, des isch doch gànz selbschtverständlich gewänn ufem Lànd. Üss denne zwei Söi het de Metzjer dànn finef Meter Brotwurscht g’màcht ! Ja doch ! friejer, bi so groβe Feschtlichkeite het m’r sich nit begniejt mit e pààr Wirschtle, naan, do het m’r in Meter kalküliert, wàs àwer uf ’ s sälwe rüsskumme n’isch. Finef Meter oder 150 Brotwirscht, wàs soll’s, furtg’schmisse isch nie nix worre. De Metzjer het dànn noch finef groβi Schwìneroulade g’màcht, het fufzig Kottlets üss denne Söi rüsgezaubert, im Fàll dàss... m’r weiss jo nie wie d’Litt Hunger hàn, un de Rescht vun denne zwei Söi het Lëwerwirschtle gän, Schwàrzwirscht oder Blutwirscht, üsser de Schinke wie m’r ing’sàlze het fer se später ze rauche.
	Des àlles isch jetz unter gueter Ufsicht in de Kiche un in de Kàmmer hinter de Kiche wie àls Kihlraum gedient het, ufg’hebt worre.

	Un de Winn ? Ja, des au isch e berechtigti Fröj. Het m’r genue Winn g’hett ? An dem därfs nit fehle, do wärd m’r jo im gànze Dorf rumkumme un obwohl m’r jede Sunndàà in d’Kirch isch un vun de Hochzitt vun Cana g’heert het wo unsere Herrgott ’ s Wàsser in Winn verwàndelt het, het m’r sich doch nit uf so e Wunder verlon welle, un, unter uns, so guet sin die Beziehunge vun denne Boddeständige Büüre zü unserem Herrgott a widder nit g’wänn, àlso het m’r vorg’sorigt. Zü däre Zit het m’r bi uns numme selbschtgemàchter Winn getrunke, m’r het nie kenner gekauft, üsseme finànzielle Grund nàdierli, àwer au weil der Winn üs de eijene Rëwe kumme n’isch in denne m’r sich johrin, johrüs geplöjt het, in denne d’Sunne einem d’Hüt zü Läder gegerbt un au de Triewel mit Zucker vollgepumt het, in denne m’r sich Froschtbille àn de Finger g’holt het wenn m’r ende Jäner schun nüss isch fer se ze schnììde, naan, der Winn het zü de Fàmilie g’heert un m’r het ihm àm Disch e Ehreplàtz reserviert wenn’s àns Fiere gànge n’isch. Un dànn, wàs fer e Stolz wenn de Dischnochber, miteme fichte Au g’sààt het, dàss er noch nie kein so guet’s Trepfel getrunke het, un, wenns niemes nix üssmàcht, dàss er gern noch e Gläsel nëmme dät... 
Schunn e Wuch vor de Hochzitt het d’Fàmilie vum Hochzitter e Fässel vun 200 Liter Wisswinn gebrocht g’hett, vun dem Taylor Blankenhorn, so dàss des Koschbàre Getränk e bissel ruehje het kenne bevor m‘rs serviert het. D’Fàmilie vun de Hochzittere, miner Groβvàdder àlso, het schun im Herbscht e Fàss vun 200 Liter Rotwinn uf d’Sit g’stellt g’hett, de 595 Oberlin, dem er noch e bissel Ersteiner Sunne mitgän het bi de Veràrweitung so dàss siner Alkoholgehàlt um e Gràd oder zwei höher worre n’isch. Also het m’r 400 Liter Winn bereit g’stellt g’hett ! Getrunke isch nàdierli nit àlles worre, àwer wie g’sààt, blàmiere het sich niemes welle...

	Do luej, d’Erschte kumme schunn. Es isch 9 Ühr vorbei. Es sin die vun Schilige wie mitem Zug kumme sin. M’r fiehrt se nin, àwer nit in d’Stub oder in d’Kiche wo se numme im Wäj g’stànde wärde, naan, sie wäre in d’Kàmmer g’fiehrt, rechts, glich nochem Ingàng. D’Kàmmer isch üsg’ruemt worre so dàss die gelàdene Gäscht ihri Kleider dert unterbringe kenne. M’r het àn àlles gedenkt. Dànn kumme die vun Schofhof. Sie kumme mit ihre vélos ! Bi dem Söiwetter ! Awer wie hätte se denn sunscht kumme sotte, es gibt ken ànderes Trànsportmittel un die pààr Trepfle... jo, do het m’r schun gànz ànderi Sàche mitgemàcht, nit wohr ? 

	Noch un noch fillt sich de Hoft mit schwàrze Bàrbli. D’Gäscht, meischtens üssem Dorf, kumme im schwàrze Sunndààkleid, mit wissem Hembd, schwàrzi Kràwàtt fer d’Männer, un d’Fraue sin im schwàrze Rock, unte drunter e neijes, wisses Bliesel, un mitem e lichte Mäntele owe driwwer weil jo nit wàrm isch àn dem Dienschdààmorje. E pààr ältere Fraue kumme noch im tràditionelle, schwàrze „Gàsseweck“, mit Bliemle g’stickt uf de Bruscht un bis unter de Bàrt zügeknepft.

	Jetz wäre schun d’“Streissle“ verteilt, die Bliemle, wiss wie de Hochzittere ihre Rock,  die m’r entweder ins Knopfloch g’steckt het oder ins Bruschtsäckel vum Fràck, un schunn, ohne dàss jemes ebbs g’sààt het, duet sich de Hochzittszug  ufstelle. D’Hochzittere isch do, sie stràhlt iwer ’ s gànze G’sicht, es isch e Pràcht fer se ànzelueje in ihrem wisse Hochzittskleid. De Schleier ufem Kopf bedeckt vornehm ihri schwàrze, zeruckg’strählte Hoor, de Hochzittsstrüss in ihre Hànd bliehjt wie d’Auje vum Hochzitter in sinem neije Kleid, mit de pàssende Kràwàtt, mit sine Hàndschueh ààn un mit sinem najelneije Huet uffem Kopf. Sie sin scheen, die zwei, e scheenes Pärel, sie pàsse zàmme.

	Schunn ruefe d’Glocke, es isch Zit fer sich uf de Wäj ze màche wenn m’r in de Zit in de Kirch ànkumme will un a nitt die Wunderfitzige wàrte màche will wie rüss uf d’Stroβ sin fer d’Hochzit ze lueje.
	
„Ja wàs isch, uf wàs wàrte n’r, de Herr Pfàrrer wurd ungeduldi, hop, es geht los !“

E gnädiger Himmel erlaubt im e Sunnestràhl die gröj Deck durchzebreche wie’s Dorf  züdeckt un de wisse Schleier vun de Hochzittere ze streichle im Moment wo d’Hochzitt, fierlich wie e Prozession, de Hoft verlosst, im e hin un herwiege vun schwàrze Hiet. Wenn e Sperwer üssem Dàsselberg rüssg’floeje wärd, hätt er e làngi, schwàrzi Raup g’sähn wie sich làngsàm, uf de nàsse Stroβ furtbewejt, àwer de Himmel het sich zügemàcht un es het widder ànfànge niessle. Ellaan, e Pärel Durteldììwle isch iwwer die Kolonn g’flöje. D’Köche, uf de Stàffel, in ihrem wisse Schurz, het de Hochzitter wie àm End vum Hochzittszug geloffe n’isch, mitere scherzhàfte Bemerikung noch emol g’foppt ; „jetzt isch rum mitem scheene Läwe, rum mit de scheene Zitt...!“ Es isch nàdierli e Scherz gewänn, so àlt wie d’Menschheit un de Hochzitter het’s a e so ufgenumme, er het gewisst, dàss die pààr Werter ihne brühige solle, un au dàss d’Köche ’ s Heft fescht im Griff het. E delikàter Duft vun Suppefleisch isch mitgànge bis àns Eck vun de Stroβ.

Obwohl ’ s Wetter unfrindlich isch, hàn sich e pààr Wunderfitzige üs de Hieser getröjt; sie stütze sich uf’s Hofdor, mànchi lehne sich mitem Buckel gàje d’Hüswànd um e bissel Schutz se sueche; sie welle d’Hochzittere bewundere, de jung Hochzitter, d’Fàmilie, d’Gäscht, àwer sie sin a do fer ze kritisiere, wie zuem Beispiel denne Huet wie nit zuem Màntel vun de Rosa pàsse duet, oder im Louis sin Kleid wie er schun vor zwànzig Johr bi sinere Hochzitt getraawe het un jetz ze eng worre n’isch, sie bemerike e jedi Kleinigkeit, beànstànde àlles, àwer des g’heert dezü, des isch schun immer so gewänn, kaaner duet sich do drààn steere. Mànchmol, hinterem e Fenschter, zieht e Hànd ’ s Fenschterdiechel zeruck un e àlter Kopf klebt sich gàje d’Schièb, luejt wie die „Jugend“ vorbei zieht, sifzt gànz tief, läjt e pààr wissi Locke zerächt, un setz sich widder näwe de Ofe, begleit vun de Andenke üs Licht un Schàtte die erscht àm Dàà vum Tod g’löscht wäre.
Un d’Hochzitt isch vor àndere Höft vorbeigànge, vor àndere Fenschter, àwwer die àlte Köpf hinte drààn hàn immer die sälwe, tiefe Fàlte g’hett un ihri Brischt hàn immer de sälb Siftzer vun sich gän. Un d’Männer im Hochzittszug hàn àlli d’sälwe Sorje g’hett mit ihrem g’stärickte wisse Hembderkraawe wie se g’hindert het ihre Kopf ze dräje un d’Fraue hàn àlli uf d’Zähn gebisse weil ihri neije Schueh e Nummer ze klein gekauft worre sin. Ja, s’Läwe isch nit einfàch, a nit àn some Feschtdàà.
M’r het d’Bekànnte begrieβt im durchgehn, m’r het sich hàlblüt iwer de Noochber unterhàlte wie sini Kueh fer e Spottpriss àm Judd àbgän het muen, m’r het iwer de Priss vum Waize g’scholte wie noch nie so dìer gewänn isch wie im Spotjohr, a iwwer d’nägscht Ernt ;

Wie steht’s mitem Waize des Johr ?
Oh! er wàchst, er wàchst.
Maansch s’gibt e scheeni Ernt ?
Wenn sich àm Jerry  e Kràbb im Korn verstecke kànn, dànn gibts e guets Johr.
Jerry isch àm 23...
Stille ! Sähn n’r nit, dàss m’r in d’Kirch nin gehn !

Un es isch Still worre wie se in d’Kirch ingeträtte sin. D’Männer hàn uf de rechte Sit Plàtz genumme, d’Fraue uf de linke, so wie sie’s schunn zitter Menschegedenke g’màcht hàn un d’Kerze un d’Lichter  hàn d’Hochzittere noch scheener erschìène màche un d’Auje vum Hochzitter hàn vor Glick geglänzt wie er näwe ihre Plàtz genumme het. Dànn het de Orgànischt d’Register gezoeje un gedruckt, un es sin unglaublich scheene, harmonische Kläng üs de Orgelpfiffe entwiche un hàn d’Kirch bis unter d’Wölbung g’fillt so dàss d’Fraue Gänshütt bekumme hàn, so riehrend isch des gewänn.
Zwei volle Stund het de Gottesdienscht geduert. De Pfàrrer het’s Kyrie àng’stimmt, d’Sänger hàn s’Gloria g’sunge, m’r het uf làtinisch gebädd un de Messdiener het de Wìhrauchkessel so gewàltig hin un her g’schwenkt, dàss sich de Wìhrauch in de gànz Kirch verteilt het un sich in d’Kleider g’setzt het wie d’Predig in d’Herze vum junge Hochzittspärel.
D’Werter vum Herr Pfàrrer sin vun de Kànzel g’fàlle, einmol messerschàrf, dànn mild un sànft, dànn widder lìèweswürdig, àwer immer uf Hochditsch.
Die Anmut einer Ehefrau bewirkt das Glück ihres Mannes... Glücklich der Mann einer vortrefflichen Frau, denn die Anzahl seiner Jahre auf dieser Welt wird verdoppelt...
Dànn het m’r uf de Männersitt heere hieschtle... offesichtlich sin nit àlli bereit gewänn fer so làng mit ihre Fraue zàmmezeblìèwe...

Liebt euch... liebt euch... liebt euch... bis dass der Tod euch scheidet...

D’Fraue hàn ihri g’stikti Nàsdiechle rüssg’holt, e pààr Männer miteme weichere Herz hàn sich mitem Ärmel e Trepfel àn ihre Nàs àbg’wischt, wàs soll’s, sie sin jo unter sich gewänn.

In de letschte Bànk uf de Männersit sin e pààr ìngenickt, meischtens d’gànz àlte, die wie schunn e pààr Hochzitte in ihrem Läwe mitgemàcht hàn g’hett, die wie d’Predigt vum Pfàrrer üssewendi gekennt hàn, die wie gewisst hàn, dàss er schunn àm Dàà devor e scheenes Stick Kàlbsroulade g’schenkt het bekumme, sowie de Schuelmeischter un a d’Krànkeschweschtere wie nie leer üssgànge sin, un ihre Menscheverstànd het ne g’sààt, dàss des guet e so isch un dàss se wenischtens noch bis zuem Sanctus widdersch schlofe kenne.

‘ s Marikel un de Güscht hàn sich ewigi Treie g’schwore, hàn d’Ring üssgetüscht, hàn sich e schéier Schmutz gän, hàn in de Sàkrischtei d’Biecher unterschriwe un sin dànn, stolz un glicklich àls Mànn un Frau d’Kirch nüss geloffe. D’Messdiener hàn ihne de Waij versperrt miteme dicke wisse Seil wie se g’spànnt g’hett hàn un dànn het e jedes wie d’Kirch nüss gewellt het e Geldstick ins Kerwel geläjt, àwer nie ze viel... m’r het gewisst wie viel Schweiβ es koscht fers ze verdiene.

Drüsse hàn sich d’Wunderfitzige ing’funde g’hett, d’junge Männer hàn ihri „Kàtzekepf“ gàje e Wànd g’stoβe um se explodiere ze màche im e firchterliche Kràch, ànderi, ufem Kirchhoft näwes drààn, hàn in d’Luft g’schosse mit ihre Jàgdflinte. Es het g’schosse un g’raucht un gedonnert wie àm Néijohr.

Dànn het sich die Raup widder in Bewejung g’setzt un e jedes het gemerickt, dàss es ufem Heimwaij schneller gànge n’isch wie im furtgehn, nit weil es berjàb gànge n’isch, naan, àwer ehnder weil e jedes àn des köschliche Esse gedenkt het wie uf se g’wàrt het. 
Es isch uf Middàà gànge wie se de Hoft nin sin wo sich niemes làng ufg’hàlte het.  M’r het schnell de Huet un de Màntel àbg’laijt un die gànz G’sellschàft het sich, ohne g’heisse, in d’“Savarin-Stub“, àn ihre reservierte Plàtz g’setzt.

Un wàs isch mitem Aperitif, heer ich eich jetz fröje ? Ich mues eich leider enttäusche, e Aperitif het m’r ufem Lànd nit gekennt, zällemols, do isch’s direkt àns Wesentliche gànge ohne Zit ze verliere mit de Näwesächlichkeite .

Wie dànn e jedes àn sinem Plàtz g’sässe n’isch, het sich s’Hochzittspärel g’stellt un het ‘ s Vàdderunser gebädd; „ Vater unser der Du bist im Himmel...“ . Tiefi Männerstimme hàn sich mit de klore Stimme vun de Fraue vermischt inre kurze Andàcht àwwer m’r het gemerikt, dàss schun e pààr gàje d’Dier g’schiehlt hàn iwerem Bädde un „s’Amen“ vum Gebädd isch untergànge im Zerächtrucke vun de Bänk wie sich d’erschte g’setzt hàn un ihri Serviette umgebunde hàn um jo ken Zit ze verliere wenn serviert wurd. M’r isch ungeduldi worre in de Stub, àwer wie sich d’Köche àn ihre Plàtz g’setzt het, näwe de Dier, jetz wo se numme noch ze iwerwàche het brüche, do het e jedes gewisst, dàss mit de Bedienung àng’fànge wurd.

Un d’Servier-Màmselle sin rin kumme mit de Fleischsupp wie bi so feschtliche Ereignisse nit fähle het därfe. E Rinderbouillon mit Màrikknepfle drinne sowie e pààr vermicelles fer ze ziere! Un fer denne ze serviere do het m’r sich nit g’scheijt fer d’Porzelàn-Suppeschissle üssem Kàschte ze hole, wàs villicht ein oder zwei Mol im e Menscheläwe vorkumme n’isch. Wàs saawe iwer die Fleischsupp ! Die het e Duft vun sich gän wie direkt üss de Scholle kumme n’isch àn denne sie so g’hànge sin, direkt üss dem Bodde wie se schwitze het màche im Summer un uf dem sie ihri Knoche g’schunde hàn ’ s gànze Johr un vun dem sie sich mit viel Miej trenne wäre, wenn se emol d’Trumpete vun Jericho ze heere bekumme. Des isch ihre Bodde gewänn un die Gähleriwle un die Ziwle un der Lauch un der Peterli wie dem Bouillon denne b’sundere G’schmàckt gän hàn sin uf ihrem Bodde g’wàchse un der Ochs wie ’ s Fleisch g’stellt het un ’ s Màriks, het uf ihre Weide gegràst. Es isch de Duft gewänn vun ihrem Bodde wie jetz üss ihre Däller sich in de Stub verbreit het, e Duft wie ihne schun ’ s Wàsser im Mül het màche zàmme laafe bevor sie numme e Leffel devun genumme hàn g’hett. Un die Fettgiggele, die hunderte vun Fettgiggele wie uf dem Bouillon g’schwumme sin ! E Bewies meh, wenn m’r einer gebrücht hätt, vun de Fruchtbàrkeit vun ihrem Bodde.

-„Heersch jetz uf mit dem Rotwinn in d’Supp ze schitte, des màcht m’r doch nit !“ 
-„Wàs bàbbelsch denn, Frau, in de Haute-Vienne hàn se’s genau so g’màcht un es isch guet g’wänn.

Un d’Schöpfleffel sin àn de Suppeschissle àng’stoβe un d’Leffel sin in d’Supp ingetaucht worre un d’Mieler hàn die haiss Supp g’schlürft un die Màriksknepfle sin in de Mieler vergànge un niemes het meh geredd, numme wenn m’r noch emol nëmme het welle un d’Suppeschissel widdersch drunte g’stànde n’isch.

Iwer des dämpfende un leckere Suppefleisch redde welle wie eringetraawe worre n’isch ufere lànge wisse Plàtt uf däre noch, in Schìwe g’schnittene hàrt-g’sottene Eier geläje sin mit Sàlzgrumbeerle drum erum, wärd verloreni Zit. Un der Meeretich, der wàrm, un der kàlt Meerettich, un noch die Schissle voll Rotràhne un Gähleriwle wie m’r im Spotjohr drüsse im Gärtel ìng’schlaawe g’hett het ! Isch des e Anblick g’wänn ! Es gibt einfàch ken Werter fer des ze b’schrìwe, naan, m’r mues es genieβe. Un des hàn se a g’màcht ohne dàss m’r ànhàlte het muen. M’r het mit Appetitt g’esse, m’r het sich e erschtes Mol serviert un het e zweites un a e drittes Mol genumme, m’r het uf d’G’sundheit vum Hochzittspärel àng’stoβe, m’r het uf d’G’sundhait vum Dischnochber getrunke un m’r het ànfànge länger ze verzähle, jetz wo de grösschte Hunger g’stillt gewänn isch un wo d’Gläser noch un noch g’leert worre sin. 

Dànn sin d’Pàschtetle ufgetraawe worre. Pàschtetle g’fillt mit Kàlbsfleisch un Hienerfleisch un Champignons, un mitere fine, wisse Soβe die einem de Geruchsinn, wie doch schun verwehnt g’wänn isch,  noch emol so richtig àngereijt het.

-« Zäj, Frau, làng m’r doch gràd ’ s Brot. »
-« Brot kànnsch dehaime esse, nëmm ehnder vun däre Füllung!“
-„Ich hàb doch schunn drei Mol genumme, ’ s Brot isch fer d’Soβe ze tunke, oder glaabsch ich loss se im Däller fer d’Kàtz. Un dànn, es gibt noch Kàlbsroulade, de Däller mues suefer sin.“

Es isch uf hàlb vier gànge wie d’Servier-Màmselle die Kàlbsroulade ringetraawe hàn. Nit aaner, naan, nit zwei, naan, àwer uf vier riesige Plàtte sin vier riesige Roulade ringetraawe worre. Un wie des Fleisch präsentiert gewänn isch ! M’r het gemaint es isch e gerollter Kueche g’fillt mit Konfitür ! Un wie sàftig des üssg’sähn het ! Un wie des g’schmeckt het ! Un dànn isch’s Lob üssg’sproche worre vum Büür wie des Kälwel geliefert het un dànn het m’r im Metzjer Komplimente g’màcht un au de Köche, m’r het de Eltere vum Hochzittspärel gràtüliert fer denne Feschtdàà un m’r het sich einfàch nit scheniert fer drei Sticker ze nëmme, numme im Fàll, dàss d’Plàtt, später nimmi vorbei kumme sott.

-„Waisch, Kumpel, es gedenkt m’r gàr nimmi wànn ich so guet un so viel getàfelt hàb...“ 

Un de Kumpel uf de àndere Sit vum Disch, mit glänzende Aue un vollem Mül het züg’stimmt ; 

-„Ich a nit, un waisch wàss, es reihjt mich gàr nit, dàss ich kumme bin...“

Un m’r het noch emol Grumbeerepürée genumme un a noch jungi Erbsle un m’r het noch emol volli Leffel Soβe erüssg’schepft un m’r het noch emol uf d’G’sundhait vum Hochzittspärel getrunke un dànn uf G’sundhait vun àlle so dàss niemes vergässe wurd un m’r het widdersch gemàcht mitem Esse, m’r het gemaant sie kumme àlli üssre längere Fàschtezitt erüs. 
-„Oh! numme noch aan Stickele fer s’Pürée ferti ze màche... „ Un glich druf ; „Zäj, làng m’r doch ’ s Pürée, gràd fer ’ s Fleisch ferti ze màche, ja, numme e Leffel voll, merci...“

Properi Däller sin üss de Stub getraawe worre un d’Köche isch zeffride gewänn. 

Mànchi stehn jetz uf fer sich d’Fies ze verträtte oder fer besser ze verdaue, denn sie wisse, dàss es jetz nimmi làng duert bis ’ s Dessert kummt.

Un ’ s Dessert isch ringetraawe worre genau in dem Moment wo de dick Sepp mit sinere Gnäscht a d’Stub rin isch. M’r het ne b’stellt g’hett, dàss er e bissel Stimmung màcht, denn e Hochzitt isch ebbs Luschtiges ! E Hochzitt ohne Müsik het’s nie gän bi uns ufem Dorf. Un de dick Sepp mit sine dicke Finger het ànfànge d’Knepf un d’Tàschte vun sinere Gnätsch ze quäle, er het se g’schunde un màrtyrisiert àwer wàs fer scheeni Tön het er däre Gnäscht entlockt ! Bi mànche hàn se so scheeni Erinnerunge geweckt, dàss ne Traene kumme sin... Un iwerem Müsik màche isch d’Vanille-Crème un d’Chocolat-Crème serviert worre un a noch vier groβi biscuits wie so wunderbàr geziert gewänn sin, dàss m’r numme noch „ah! „ un „oh!“  g’heert het in de Stub. Un dànn sin so groβi Sticker g’schnitte worre, dàss m’r e finfter hole het muen, àwer schlimm isch des nit gewänn, m’r het e Dutzet gebàcke g’hett.

-“Zäj, Sepp, spiel doch uns denne noch emol wie bi unsere Hochzitt g’spielt hesch, waisch noch ?“

De Sepp het sich nàdierli nimmi erinnert àn des wàs er schunn uf de Hochzitte g’spielt g’hett het, àwer er het so g’màcht wie un het g’làcht un het widder ànfànge uf de Tàschte rum ze  hämmere un d’Alte hàn sich àn ihri Jugend erinnert un d’Junge hàn sich àmüsiert un e Groβel im Eck het d’Aue zü gemàcht un het de Bàrt in ihre Gàsseweck gedruckt, hättsch g’maant sie isch in de Kirch, so àndächtig het se däre Melodie züg’heert. Es sin ihri Lìèdle gewän, es sin ihri Melodie g’wänn wie de dick Sepp g’spielt het.
Dànn sin noch zwei Flàsche Chàmpàgner ufg’màcht worre, numme fer e àndere G’schmàck im Müll  ze bekumme...

Es het sechs g’schlaawe g’hett uf de Kircheühr wie e pààr Mànnsbilder sich uf de Heimwaij g’màcht hàn fer ze fietere un fer ze melke, ànderi hàn die Arweit ihre Fraue delegiert, àwer m’r het versproche sich glich nochem Melke in de Wirtschàft ze treffe. 
Uf des hin, het ’ s Hochzittspärel ’ s Signàl zuem Ufbruch gän un d’gànz G’sellschàft het sich uf de Waij g’màcht, nimmi so in de Raihj wie àm Morje, àwwer e jedes isch g’loffe mit dem wie er sich àm beschte verstànde het oder mit dem wie er noch nit d’G’laijehait g’hett het fer ze verzähle. 
De Sepp isch vorne drààn häre gànge un het g’spielt un g’sunge, un so isch die luschtig G’sellschàft  in de „Anker“ wo m’r getànzt het, getrunke het, un dànn het de Hochzitter denne Anwesende in de Wirtschàft e „tournée“ beràppt, weils e so mode gewänn isch un sofort isch‘s widder losgànge in d’“Bàhnwirtschàft“ wo sich des Gànze widerholt het. Dànn sin se noch zuem „Deitsche Michel“ un zü äre Zit wo mànchi schun im Bett geläje sin, sin se ins „Làmm“. Sie hätte a noch ins Restaurant „Au bon ami“ g’sott, de Anstànd hätts verlàngt, àwer weil m’r sich so làng in de àndere Wirtschàfte ufg’hàlte g’hett het, isch’s spot worre un schunn isch so e Kichehilf kumme un het g’sààt, dàss dehaime ’ s Nàchtesse wàrt.

Kànn m’r do „naan“ saawe wenn m’r weiss, dàss dehaime ’ s Esse villicht schunn kàlt wurd ? Un so het m’r sich uf de Stell uf de Heimwaij g’màcht. Bi mànche isch’s guet gànge, bi àndere wenijer guet, un die, obwohl sie nie nix vun de Theorie vum Copernic g’heert g’hett hàn un d’Aànziehjungskràft vun de Erd fer sie e unerforschtes Gebiet gewänn isch, hätte däre ihre Tribut zàhle muen wenn nit e kräftiger Arm vun ihre Frau sie unterstizt hätt...

-„Ah! un dü hesch m’r doch g’sààt dü trinksch nix meh !
-„Ich hàb jo nix getrunke Frau, numme e Gläsel voll, fröj doch de Sepp...

E hàlb Stund druf sin àlli widder in de Stub àn ihre Plätz g’sässe un sie hàn sich sofort àn e Plàtt voll Suerkrütt herg’màcht uf däre zwei Dutzend Brotwirscht gelaije sin. Un sie hàn noch emol g’esse, dàss es e Fraid gewänn isch züzelueje. Drei Plàtte voll sin verdàchst worre un de Sepp het g’spielt un àlli hàn g’sunge un de Groβvàdder het wie immer bi so Feschtlichkeite de ; „Ich bin de Doktor Eisenbart“  àng’stimmt, àwer wie immer e Oktave ze hoch, so dàss er noch emol ànfànge het muen, unter de spöttische Bemerikunge vun de Gäscht, àwwer des het ihm nix üssg’màcht. Es isch zweie gewänn àm Morje wie e letschtes Glàs Himbeerelikör ing’schenkt worre n’isch un dànn hàn sich àlli zeffride uf de Heimwaij g’màcht. 
’ s Junge Pärel het schun vorhäre prowiert fer sich üssem Staub ze màche, àwwer m’r het ufgepàsst un wie se dànn endli vor ihrem Bett g’stànde sin, hàn se festelle muen, dàss es àbg’schlaawe gewänn isch. Wàs soll’s, de Hochzitter het in d’Händ g’spitzt un hets widder zàmme montiert, er het jo die erscht Nàcht mit sinem Marikel nit ufem Bodde verbringe welle.

Am àndere Dàà, middààs, hàn die zwei serviert, so isch’s gewänn, zällemols. Alli sin se widder kumme. De Appetitt isch nimmi so groβ gewänn wie àm Dàà devor, àwer es isch immer e leeri Plàtt zeruckgànge in d’Kiche un die Schwìèneroulädle hàn genau so viel Anhänger g’hett wie d’Kàlbsroulädle àm Dàà züvor. M’r isch unter Kenner g’wänn!

Awer wie’s hàlt so isch, au die G’schicht het e End. Oder soll ich noch emol verzähle wàs àm Mittwoch un àm Dunnerschdàà g’esse un getrunke worre n’isch ? Naan, des dät ze viel Plàtz nëmme, wisse sotte n’r àwwer trotzdem, dàss d’Letschte àm Friddàoowe haime sin un dàss de Güscht un ’ s Marikel glicklich gewänn sin solàng wie’s ihne de Himmel erlaubt het.